using System.Text;
using Ark.Core.Metadata;
using Ark.Core.Sync;
using Ark.Core.Typing;
using Ark.Providers.Abstractions;

namespace Ark.Providers.PostgreSQL;

public sealed class PostgreSqlDdlGenerator : IDdlGenerator
{
    public ArkDialect Dialect => ArkDialect.PostgreSQL;

    public string Quote(string identifier) => "\"" + identifier.Replace("\"", "\"\"") + "\"";

    public string TableName(TableRef t)
    {
        var schema = string.IsNullOrEmpty(t.Schema) ? "public" : t.Schema;
        return Quote(schema) + "." + Quote(t.Table);
    }

    public IReadOnlyList<string> CreateTable(TableRef target, CanonicalTable t, List<string> warnings)
    {
        // 把无条件定的表名替换为 schema/库限定名（不破坏 Quote 的引号转义）
        var unqualified = Quote(t.Name);
        return CreateTable(t, warnings)
            .Select(s => s.Replace(unqualified, TableName(target), StringComparison.Ordinal))
            .ToList();
    }

    public IReadOnlyList<string> CreateTable(CanonicalTable t, List<string> warnings)
    {
        var statements = new List<string>();
        var sb = new StringBuilder();
        sb.Append("CREATE TABLE IF NOT EXISTS ").Append(Quote(t.Name)).AppendLine(" (");
        var defs = new List<string>();
        foreach (var col in t.Columns)
        {
            var def = ColumnDef(col, t, warnings);
            if (def is { } d) defs.Add("    " + d);
        }
        if (t.PrimaryKeyColumns.Count > 0)
            defs.Add("    PRIMARY KEY (" + string.Join(", ", t.PrimaryKeyColumns.Select(Quote)) + ")");
        sb.AppendLine(string.Join(",\n", defs));
        sb.Append(");");
        statements.Add(sb.ToString());

        foreach (var col in t.Columns.Where(c => c.Comment is { }))
            statements.Add($"COMMENT ON COLUMN {Quote(t.Name)}.{Quote(col.Name)} IS '{col.Comment!.Replace("'", "''")}';");

        return statements;
    }

    /// <summary>列定义；生成列缺表达式时返回 null 并写警告。</summary>
    private string? ColumnDef(CanonicalColumn col, CanonicalTable t, List<string> warnings)
    {
        var sb = new StringBuilder(Quote(col.Name)).Append(' ');
        if (col.IsAutoIncrement)
        {
            if (col.Type.Id is CanonicalTypeId.Int16 or CanonicalTypeId.Int32 or CanonicalTypeId.Int64)
                sb.Append(TypeMapper.FromCanonical(col.Type, ArkDialect.PostgreSQL).Sql);
            else
            {
                warnings.Add($"列 {col.Name}: 自增列类型 {col.Type} 非整数，已改用 bigint identity");
                sb.Append("bigint");
            }
            sb.Append(" GENERATED BY DEFAULT AS IDENTITY");
            return sb.ToString();
        }

        var mapping = TypeMapper.FromCanonical(col.Type, ArkDialect.PostgreSQL);
        warnings.AddRange(mapping.Warnings.Select(w => $"列 {col.Name}: {w}"));
        sb.Append(mapping.Sql);

        if (col.IsGenerated)
        {
            if (col.GeneratedExpression is { } expr)
            {
                sb.Append(" GENERATED ALWAYS AS (").Append(expr).Append(") STORED");
                return sb.ToString();
            }
            warnings.Add($"列 {col.Name}: 生成列缺少表达式，已按普通列创建");
        }

        if (!col.Nullable) sb.Append(" NOT NULL");
        if (col.DefaultKind != ValueExprKind.None && col.DefaultValueSql is { } d)
        {
            var emitted = FunctionTranslator.Emit(ArkDialect.PostgreSQL, col.DefaultKind, d);
            if (emitted is null)
                warnings.Add($"列 {col.Name}: 默认值 {d} 无法在 PostgreSQL 表达，已忽略");
            else
                sb.Append(" DEFAULT ").Append(emitted);
        }
        return sb.ToString();
    }

    public IReadOnlyList<string> AlterTable(TableDiff diff, List<string> warnings)
    {
        var statements = new List<string>();
        var table = TableName(diff.Target);

        foreach (var col in diff.AddedColumns)
        {
            var def = ColumnDef(col, diff.After, warnings);
            if (def is not null) statements.Add($"ALTER TABLE {table} ADD COLUMN {def};");
        }

        foreach (var col in diff.DroppedColumns)
            statements.Add($"ALTER TABLE {table} DROP COLUMN {Quote(col.Name)};");

        foreach (var change in diff.AlteredColumns)
        {
            var before = change.Before;
            var after = change.After;
            var clause = BuildAlterColumn(table, before, after, warnings);
            statements.AddRange(clause);
        }

        if (diff.PrimaryKeyChanged)
            warnings.Add("PostgreSQL 主键变更涉及删除/重建约束与索引，v1 请人工处理");

        return statements;
    }

    private List<string> BuildAlterColumn(string table, CanonicalColumn before, CanonicalColumn after, List<string> warnings)
    {
        var statements = new List<string>();
        var col = Quote(after.Name);

        if (!Equals(before.Type, after.Type))
        {
            var mapping = TypeMapper.FromCanonical(after.Type, ArkDialect.PostgreSQL);
            warnings.AddRange(mapping.Warnings.Select(w => $"列 {after.Name}: {w}"));
            statements.Add($"ALTER TABLE {table} ALTER COLUMN {col} TYPE {mapping.Sql} USING {col}::{mapping.Sql};");
            warnings.Add($"列 {after.Name}: 类型变更 {before.Type} → {after.Type} 可能截断/转换失败现有数据");
        }

        if (before.Nullable != after.Nullable)
            statements.Add(after.Nullable
                ? $"ALTER TABLE {table} ALTER COLUMN {col} DROP NOT NULL;"
                : $"ALTER TABLE {table} ALTER COLUMN {col} SET NOT NULL;");

        if (!string.Equals(before.DefaultValueSql, after.DefaultValueSql, StringComparison.OrdinalIgnoreCase))
        {
            if (after.DefaultKind != ValueExprKind.None && after.DefaultValueSql is { } d)
            {
                var emitted = FunctionTranslator.Emit(ArkDialect.PostgreSQL, after.DefaultKind, d);
                if (emitted is null)
                    warnings.Add($"列 {after.Name}: 默认值 {d} 无法在 PostgreSQL 表达，已忽略");
                else
                    statements.Add($"ALTER TABLE {table} ALTER COLUMN {col} SET DEFAULT {emitted};");
            }
            else if (after.DefaultValueSql is null)
            {
                statements.Add($"ALTER TABLE {table} ALTER COLUMN {col} DROP DEFAULT;");
            }
        }

        return statements;
    }

    public IReadOnlyList<string> CreateIndex(CanonicalIndex idx, TableRef t, CanonicalTable? table = null)
    {
        var sql = $"CREATE {(idx.IsUnique ? "UNIQUE " : "")}INDEX IF NOT EXISTS {Quote(idx.Name)} ON {TableName(t)} " +
                  $"({string.Join(", ", idx.Columns.Select(Quote))})";
        return [sql + ";"];
    }

    public IReadOnlyList<string> DropIndex(string indexName, TableRef t) =>
        [$"DROP INDEX IF EXISTS {(string.IsNullOrEmpty(t.Schema) ? "public" : t.Schema)}.{Quote(indexName)};"];

    public IReadOnlyList<string> DropTable(TableRef t) =>
        [$"DROP TABLE IF EXISTS {TableName(t)};"];

    public IReadOnlyList<string> CreateForeignKey(CanonicalForeignKey fk, TableRef t)
    {
        var sql = $"ALTER TABLE {TableName(t)} ADD CONSTRAINT {Quote(fk.Name)} FOREIGN KEY " +
                  $"({string.Join(", ", fk.Columns.Select(Quote))}) REFERENCES {QualifyRef(fk.ReferencedTable)} " +
                  $"({string.Join(", ", fk.ReferencedColumns.Select(Quote))})" +
                  (fk.OnDelete is { } od && od != "NO ACTION" ? $" ON DELETE {od}" : "") +
                  (fk.OnUpdate is { } ou && ou != "NO ACTION" ? $" ON UPDATE {ou}" : "");
        return [sql + ";"];
    }

    public IReadOnlyList<string> DropForeignKey(string fkName, TableRef t) =>
        [$"ALTER TABLE {TableName(t)} DROP CONSTRAINT {Quote(fkName)};"];

    public IReadOnlyList<string> TruncateTable(TableRef t) => [$"TRUNCATE TABLE {TableName(t)};"];

    public IReadOnlyList<string> ResetAutoIncrement(TableRef t, string pkColumn, long value) =>
        [$"SELECT setval(pg_get_serial_sequence('{TableName(t).Replace("\"", "")}', '{pkColumn}'), {value}, true);"];

    /// <summary>引用表可能带 schema/库前缀（如 ark_sync.users）：分段引号，避免整体引成一个标识符。</summary>
    private string QualifyRef(string referenced)
    {
        var parts = referenced.Split('.');
        return string.Join(".", parts.Select(Quote));
    }
}
