/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectionDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SaveConnectionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectionDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectionDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SaveConnectionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectionDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TestConnectionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SaveConnectionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TestConnectionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{id}/databases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DatabaseInfo"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{id}/databases/{db}/schemas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    db: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SchemaInfo"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{id}/databases/{db}/schemas/{schema}/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    db: string;
                    schema: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TableSummary"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    db: string;
                    schema: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTableRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DdlExecuteResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{id}/databases/{db}/schemas/{schema}/tables/{table}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    db: string;
                    schema: string;
                    table: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TableDetailResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    db: string;
                    schema: string;
                    table: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AlterTableRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DdlExecuteResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    db: string;
                    schema: string;
                    table: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DdlExecuteResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{id}/databases/{db}/schemas/{schema}/tables/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    db: string;
                    schema: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTableRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DdlPreviewResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{id}/databases/{db}/schemas/{schema}/tables/{table}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    db: string;
                    schema: string;
                    table: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AlterTableRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DdlPreviewResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{id}/databases/{db}/schemas/{schema}/tables/{table}/rows/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    db: string;
                    schema: string;
                    table: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RowQueryRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RowPage"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{id}/databases/{db}/schemas/{schema}/tables/{table}/rows/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    db: string;
                    schema: string;
                    table: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RowChangeSet"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApplyChangesResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{id}/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExecuteSqlRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QueryResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SyncPlanRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SyncPlanResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown[];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SyncExecuteRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{id}/databases/{db}/schemas/{schema}/tables/{table}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    db: string;
                    schema: string;
                    table: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExportRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{id}/databases/{db}/schemas/{schema}/tables/{table}/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    format?: string;
                    batchSize?: number | string;
                };
                header?: never;
                path: {
                    id: string;
                    db: string;
                    schema: string;
                    table: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        file: components["schemas"]["IFormFile"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AlterTableRequest: {
            table: components["schemas"]["CanonicalTable"];
            execute?: boolean;
        };
        ApplyChangesResponse: {
            /** Format: int32 */
            inserted: number | string;
            /** Format: int32 */
            updated: number | string;
            /** Format: int32 */
            deleted: number | string;
        };
        /** @enum {unknown} */
        ArkDialect: "PostgreSQL" | "MySQL" | "SQLite";
        CanonicalColumn: {
            name: string;
            type: components["schemas"]["CanonicalType"];
            nullable?: boolean;
            defaultValueSql?: null | string;
            defaultKind?: components["schemas"]["ValueExprKind"];
            isAutoIncrement?: boolean;
            isPrimaryKey?: boolean;
            comment?: null | string;
            isGenerated?: boolean;
            generatedExpression?: null | string;
        };
        CanonicalForeignKey: {
            name: string;
            columns: string[];
            referencedTable: string;
            referencedColumns: string[];
            onDelete?: null | string;
            onUpdate?: null | string;
        };
        CanonicalIndex: {
            name: string;
            columns: string[];
            isUnique?: boolean;
            isPrimaryKey?: boolean;
            method?: null | string;
            whereClause?: null | string;
        };
        CanonicalTable: {
            name: string;
            columns: components["schemas"]["CanonicalColumn"][];
            primaryKeyColumns?: string[];
            indexes?: components["schemas"]["CanonicalIndex"][];
            foreignKeys?: components["schemas"]["CanonicalForeignKey"][];
            comment?: null | string;
            options?: {
                [key: string]: string;
            };
            isView?: boolean;
        };
        CanonicalType: {
            id: components["schemas"]["CanonicalTypeId"];
            /** Format: int32 */
            length?: null | number | string;
            /** Format: int32 */
            precision?: null | number | string;
            /** Format: int32 */
            scale?: null | number | string;
        };
        /** @enum {unknown} */
        CanonicalTypeId: "Boolean" | "Int16" | "Int32" | "Int64" | "Decimal" | "Single" | "Double" | "Char" | "VarChar" | "Text" | "Date" | "Time" | "DateTime" | "DateTimeOffset" | "Binary" | "Guid" | "Json" | "Xml" | "Unknown";
        ConnectionDto: {
            /** Format: uuid */
            id: string;
            name: string;
            dialect: components["schemas"]["ArkDialect"];
            host: null | string;
            /** Format: int32 */
            port: null | number | string;
            username: null | string;
            hasPassword: boolean;
            database: null | string;
            filePath: null | string;
            readOnly: boolean;
            options: {
                [key: string]: string;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ConversionIssue: {
            severity: string;
            message: string;
        };
        CreateTableRequest: {
            table: components["schemas"]["CanonicalTable"];
            execute?: boolean;
        };
        DatabaseInfo: {
            name: string;
        };
        DataPlan: {
            method: components["schemas"]["DataSyncMethod"];
            hasPrimaryKey?: boolean;
            /** Format: int64 */
            estimatedRows?: null | number | string;
            warnings?: string[];
        };
        /** @enum {unknown} */
        DataSyncMethod: "FullCopy" | "RowDiff";
        DdlAction: {
            id: string;
            kind: string;
            summary: string;
            sql: string;
            isDestructive?: boolean;
            warnings?: string[];
        };
        DdlExecuteResponse: {
            statements: string[];
            /** Format: int32 */
            executed: number | string;
            errors: string[];
        };
        DdlPreviewResponse: {
            statements: string[];
            warnings: string[];
        };
        ExecuteSqlRequest: {
            database: string;
            schema?: null | string;
            sql: string;
            /** Format: int32 */
            maxRows?: number | string;
            /** Format: int32 */
            timeoutSeconds?: number | string;
        };
        ExportRequest: {
            format: string;
            /** Format: int64 */
            limit: null | number | string;
        };
        ExtensionDependency: {
            name: string;
            installSql: string;
            present?: boolean;
            note?: null | string;
        };
        FilterClause: {
            column: string;
            op: string;
            value?: null | components["schemas"]["JsonElement"];
            values?: null | unknown[];
        };
        /** Format: binary */
        IFormFile: string;
        ImportResult: {
            table: string;
            /** Format: int64 */
            inserted: number | string;
            tableCreated: boolean;
            warnings: string[];
        };
        JsonElement: unknown;
        OrderClause: {
            column: string;
            descending: boolean;
        };
        QueryColumn: {
            name: string;
            dataType: string;
        };
        QueryResponse: {
            resultSets: components["schemas"]["QueryResultSet"][];
            messages: string[];
            /** Format: double */
            elapsedMs: number | string;
        };
        QueryResultSet: {
            columns: components["schemas"]["QueryColumn"][];
            rows: unknown[][];
            /** Format: int32 */
            affectedRows: number | string;
        };
        RowChangeSet: {
            inserts?: components["schemas"]["RowInsert"][];
            updates?: components["schemas"]["RowUpdate"][];
            deletes?: components["schemas"]["RowDelete"][];
        };
        RowDelete: {
            key: Record<string, never>;
        };
        RowInsert: {
            values: Record<string, never>;
        };
        RowPage: {
            columns: components["schemas"]["QueryColumn"][];
            rows: unknown[][];
            /** Format: int64 */
            total: number | string;
            /** Format: int32 */
            limit: number | string;
            /** Format: int32 */
            offset: number | string;
            primaryKeyColumns: string[];
        };
        RowQueryRequest: {
            /** Format: int32 */
            limit?: number | string;
            /** Format: int32 */
            offset?: number | string;
            filters?: components["schemas"]["FilterClause"][];
            orderBy?: components["schemas"]["OrderClause"][];
        };
        RowUpdate: {
            key: Record<string, never>;
            values: Record<string, never>;
        };
        SaveConnectionRequest: {
            name: string;
            dialect?: components["schemas"]["ArkDialect"];
            host?: null | string;
            /** Format: int32 */
            port?: null | number | string;
            username?: null | string;
            password?: null | string;
            database?: null | string;
            filePath?: null | string;
            readOnly?: boolean;
            options?: null | {
                [key: string]: string;
            };
        };
        SchemaInfo: {
            name: string;
        };
        SyncExecuteRequest: {
            plan: components["schemas"]["SyncPlanRequest"];
            skipActionIds?: string[];
            confirmDestructive?: boolean;
        };
        /** @enum {unknown} */
        SyncMode: "StructureOnly" | "StructureAndData";
        SyncPlanRequest: {
            /** Format: uuid */
            sourceConnectionId: string;
            sourceDatabase: string;
            /** Format: uuid */
            targetConnectionId: string;
            targetDatabase: string;
            mode?: components["schemas"]["SyncMode"];
            dataMethod?: components["schemas"]["DataSyncMethod"];
            dropExtraTables?: boolean;
            deleteExtraRows?: boolean;
            truncateBeforeCopy?: boolean;
            alignAutoIncrement?: boolean;
            /** Format: int32 */
            batchSize?: number | string;
            tables: components["schemas"]["TableSelection"][];
        };
        SyncPlanResponse: {
            sourceDialect: components["schemas"]["ArkDialect"];
            targetDialect: components["schemas"]["ArkDialect"];
            tables: components["schemas"]["TablePlan"][];
        };
        TableDetailResponse: {
            table: components["schemas"]["CanonicalTable"];
            createSql: null | string;
        };
        TablePlan: {
            source: components["schemas"]["TableSelection"];
            target: components["schemas"]["TableSelection"];
            targetTableExists?: boolean;
            structureActions?: components["schemas"]["DdlAction"][];
            data?: null | components["schemas"]["DataPlan"];
            conversionIssues?: components["schemas"]["ConversionIssue"][];
            extensions?: components["schemas"]["ExtensionDependency"][];
        };
        TableSelection: {
            database: string;
            schema?: null | string;
            table: string;
        };
        TableSummary: {
            name: string;
            kind: string;
            /** Format: int64 */
            estimatedRows: null | number | string;
        };
        TestConnectionResponse: {
            success: boolean;
            serverVersion: null | string;
            /** Format: double */
            elapsedMs: number | string;
            error: null | string;
        };
        /** @enum {unknown} */
        ValueExprKind: "None" | "Literal" | "CurrentTimestamp" | "CurrentDate" | "CurrentTime" | "UuidV4" | "Coalesce" | "Concat" | "Unrecognized";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
