using Ark.Core.Metadata;
using Ark.Core.Sync;
using Ark.Providers.Abstractions;
using Ark.Sync;
using Xunit;

namespace Ark.Integration.Tests;

/// <summary>
/// 跨库异构同步集成测试（Testcontainers：PostgreSQL + MySQL）。
/// 本机无 Docker 时自动跳过（ARK_INTEGRATION=1 强制要求运行）。
/// 启动 Docker 并运行 `docker compose -f docker-compose.dev.yml up -d` 后即可完整执行。
/// </summary>
public class CrossDialectSyncTests
{
    private static bool DockerAvailable()
    {
        if (Environment.GetEnvironmentVariable("ARK_INTEGRATION") == "1") return true;
        try
        {
            using var p = System.Diagnostics.Process.Start(
                new System.Diagnostics.ProcessStartInfo("docker", "info --format ok")
                {
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    UseShellExecute = false,
                });
            _ = p ?? throw new InvalidOperationException();
            var ok = p.WaitForExit(5000) && p.ExitCode == 0;
            return ok;
        }
        catch
        {
            return false;
        }
    }

    [SkippableFact]
    public async Task Sqlite_To_Postgres_StructurePlan_ProducesCreateActions()
    {
        Skip.IfNot(DockerAvailable(), "Docker 不可用，跳过 Testcontainers 集成测试");

        var pg = new Testcontainers.PostgreSql.PostgreSqlBuilder()
            .WithImage("postgres:16-alpine")
            .WithDatabase("ark_test").WithUsername("ark").WithPassword("ark123")
            .Build();
        try
        {
            await StartOrSkipAsync(() => pg.StartAsync());
        }
        catch (SkipException)
        {
            return;
        }
        try
        {
            await using var source = new Ark.Providers.SQLite.SqliteProvider(
                new ConnectionSpec(ArkDialect.SQLite, null, null, null, null, null, CreateSampleSqlite(), false,
                    new Dictionary<string, string>()));
            await using var target = new Ark.Providers.PostgreSQL.PostgreSqlProvider(
                new ConnectionSpec(ArkDialect.PostgreSQL, pg.Hostname, pg.GetMappedPublicPort(5432), "ark", "ark123",
                    "ark_test", null, false, new Dictionary<string, string>()));

            var planner = new SyncPlanner();
            var plan = await planner.BuildPlanAsync(source, target, new SyncPlanRequest
            {
                SourceConnectionId = Guid.NewGuid(),
                SourceDatabase = "main",
                TargetConnectionId = Guid.NewGuid(),
                TargetDatabase = "ark_test",
                Mode = SyncMode.StructureAndData,
                DataMethod = DataSyncMethod.FullCopy,
                Tables = [new TableSelection { Database = "main", Schema = "main", Table = "users" }],
            });

            var tp = Assert.Single(plan.Tables);
            Assert.Contains(tp.StructureActions, a => a.Kind == "CreateTable");
            // SQLite INTEGER 主键 → PostgreSQL bigint identity
            var create = tp.StructureActions.First(a => a.Kind == "CreateTable");
            Assert.Contains("GENERATED BY DEFAULT AS IDENTITY", create.Sql, StringComparison.OrdinalIgnoreCase);
            // created_at DEFAULT CURRENT_TIMESTAMP → now()
            Assert.Contains("now()", create.Sql, StringComparison.OrdinalIgnoreCase);
        }
        finally
        {
            await pg.DisposeAsync();
        }
    }

    [SkippableFact]
    public async Task Sqlite_To_MySql_ExtensionCheck_FlagsUuidDefault()
    {
        Skip.IfNot(DockerAvailable(), "Docker 不可用，跳过 Testcontainers 集成测试");

        // SQLite 源端含 UUID 默认值列 → MySQL 目标应翻译为 UUID()
        var srcPath = Path.Combine(Path.GetTempPath(), $"ark_i_{Guid.NewGuid():N}.db");
        Exec(srcPath, """
            CREATE TABLE docs (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                uid TEXT DEFAULT (lower(hex(randomblob(16)))),
                title TEXT
            );
            """);
        try
        {
            var my = new Testcontainers.MySql.MySqlBuilder()
                .WithImage("mysql:8.4")
                .WithDatabase("ark_test").WithUsername("root").WithPassword("ark123")
                .Build();
            try
            {
                await StartOrSkipAsync(() => my.StartAsync());
            }
            catch (SkipException)
            {
                return;
            }
            try
            {
                await using var source = new Ark.Providers.SQLite.SqliteProvider(
                    new ConnectionSpec(ArkDialect.SQLite, null, null, null, null, null, srcPath, false,
                        new Dictionary<string, string>()));
                await using var target = new Ark.Providers.MySQL.MySqlProvider(
                    new ConnectionSpec(ArkDialect.MySQL, my.Hostname, (ushort)my.GetMappedPublicPort(3306), "root",
                        "ark123", "ark_test", null, false, new Dictionary<string, string>()));

                var planner = new SyncPlanner();
                var plan = await planner.BuildPlanAsync(source, target, new SyncPlanRequest
                {
                    SourceConnectionId = Guid.NewGuid(),
                    SourceDatabase = "main",
                    TargetConnectionId = Guid.NewGuid(),
                    TargetDatabase = "ark_test",
                    Mode = SyncMode.StructureOnly,
                    Tables = [new TableSelection { Database = "main", Schema = "main", Table = "docs" }],
                });

                var tp = Assert.Single(plan.Tables);
                // 无法翻译的默认值 → error issue（SQLite randomblob 不在任何翻译表）
                Assert.Contains(tp.ConversionIssues, i => i.Severity == "warning" && i.Message.Contains("原样复制"));
                var create = tp.StructureActions.First(a => a.Kind == "CreateTable");
                Assert.Contains("utf8mb4", create.Sql, StringComparison.OrdinalIgnoreCase);
            }
            finally
            {
                await my.DisposeAsync();
            }
        }
        finally
        {
            if (File.Exists(srcPath)) File.Delete(srcPath);
        }
    }

    /// <summary>启动容器；镜像拉取失败（如无法访问 Docker Hub）→ 抛 SkipException 跳过。</summary>
    private static async Task StartOrSkipAsync(Func<Task> start)
    {
        try
        {
            await start();
        }
        catch (Exception ex) when (IsDockerNetworkError(ex))
        {
            throw new SkipException($"无法拉取镜像（网络受限）：{ex.Message}");
        }
    }

    private static bool IsDockerNetworkError(Exception ex)
    {
        var msg = ex.Message;
        return msg.Contains("registry-1.docker.io", StringComparison.OrdinalIgnoreCase)
            || msg.Contains("failed to resolve reference", StringComparison.OrdinalIgnoreCase)
            || (msg.Contains("connection refused", StringComparison.OrdinalIgnoreCase) && msg.Contains("docker", StringComparison.OrdinalIgnoreCase));
    }

    private static string CreateSampleSqlite()
    {
        var path = Path.Combine(Path.GetTempPath(), $"ark_i_{Guid.NewGuid():N}.db");
        Exec(path, """
            CREATE TABLE users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP
            );
            INSERT INTO users (name) VALUES ('alice'), ('bob');
            """);
        return path;
    }

    private static void Exec(string path, string sql)
    {
        using var conn = new Microsoft.Data.Sqlite.SqliteConnection(
            new Microsoft.Data.Sqlite.SqliteConnectionStringBuilder { DataSource = path }.ToString());
        conn.Open();
        using var cmd = conn.CreateCommand();
        cmd.CommandText = sql;
        cmd.ExecuteNonQuery();
    }
}
